sudo: false
language: ruby
services:
  - docker
before_install:
  - git clone --depth 1 https://github.com/seiferma/Docker_BuildUtils.git /tmp/BuildUtils
  - . /tmp/BuildUtils/travisSetup.sh
script:
  - travisBuildDockerhub.sh
deploy:
  provider: script
  script: travisDeployDockerhub.sh
  on:
    branch: master
env:
  global: 
    - IMAGE_NAME=seiferma/netdata
    - secure: "F7eVqo+S1GNkfkmZyiP4hR8KJuc1S9s6+wJgVh64gezGUMu6gjkYvMRUMoGrqea7yakA+aP+w9Q0lO20TDDVSZXNlXZUSY70nB3/v/TQLqTzI7QABJNZvBomH/9yoNc6vh0X8Pdr8jXO4vG1XX8Xh87spECMM7zURnBM7cj3I82uJH/cTNK8uc+g6rcYSUEIZC1p2KmCOKYN30dsZxlAhNElVp5ZQM92VuFk7kro4SCM+DcoAdFu3Cn/crhXovhNUDdDHr1w2y3R3q7TamM/NeQCvgk9Eniaiv4jJXzaqouLOIrtgJlODail/4/xXmPvkTzY950DTgrRdsTAk5Z0y2DjSAmdq1I+1E6BFTqqTRljwxWeY0LI7E3wCCG8B6S2NaS9jBLWfdwj43KSbEO0Fh2zWJWTtbOz9/+J5SIp9XswyrMp1WnVofp6rqiI3J4B4VKIjvN/rjUpkoaT3J238y29RRByKW/1X+dIyG9OXFG/eQAq0quNJTh3A03yHKOrvo7gBFz+CFp+KHnx1+HUgdzV7VVIf41szMqZ9GuXi7LnFVxnjSH/dc0tyzosYA0lt4arwRDNOSN+eafuySSUZO3NlMPCfYFt+HjrCMP9EurLNgQNbF36wVCpbUQR6SCWs6l7Ol4uWFLTsTFzLb7gOYc1tTYp7pynRD2iyJEbHd4="
